### ISSUE TITLE
Bibliography / References / Citations slide

### ISSUE THREAD

**Issue by jpfairbanks** [agoldst/elsmd#3]
Thanks for sharing this great system!

How does one create a references slide at the end of the presentation? I am trying to use the notes style of markdown input.

With this in the yaml section

```yaml

biblatex: true
biblatex-chicago: false
bibliography: ../sources.bib

```

```markdown
# References

\bibliography{path/to/sources}
```
does not seem to work.
